### ISSUE TITLE
Create robot.py with basic structure.

### ISSUE THREAD

**Issue by tuffinmuffin** [Raptacon/Robot-2020#2]
Create Basic Robot.py file for us to start expanding on.

Exit Criteria
- [x] Robot.py is created
- [x] Robot.py runs in sim
- [x] Robot.py passes tests

**Comment by tuffinmuffin** [comment]
See https://github.com/Raptacon/Robot-2020/issues/4 for starting code

**Comment by DrKittyKat** [comment]
I'm pretty sure @tuffinmuffin did all of this
