### ISSUE TITLE
Magic Robot Drive Train Working

### ISSUE THREAD

**Issue by ChrisHirsch** [Raptacon/Robot-2020#30]
Get the Drive Train working using Magic Robot
- [x] - Design class structure on Whiteboard
- [x] - Pass in controller values and get out motor speeds
- [x] - Unit tests to show passing in values and getting motor speeds

**Comment by DrKittyKat** [comment]
Currently set up to accept values and run based on that

**Comment by DrKittyKat** [comment]
in branch basic-drivetrain
