### ISSUE TITLE
Create sample PI(D) position controller motor example with built in talon SRX encoder

### ISSUE THREAD

**Issue by tuffinmuffin** [Raptacon/Robot-2020#6]
Create a sample motor configuration for use with PI(D) positional motor and talon SRX

Exit:
Updated Motor creator helper as needed to be fully functional
Create an example motor.
Test on hardware with Talon SRX
Create pull request to be reviewed

**Comment by Team3200** [comment]
Pull request: https://github.com/Raptacon/Robot-2019/pull/23
The example motor is the 'right motor'
This is fully functional

**Comment by Team3200** [comment]
Technically, this is for velocity but it works if the control mode is changed to position.
